version: '3.8'

services:

  haproxy:
    image: haproxy:alpine
    container_name: ${PROJECT_NAME}_haproxy
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs:ro
    networks:
      public_net:
          ipv4_address: ${HAPROXY_IP}

  app01:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app01
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE1_IP}
          aliases: 
              - app01

  app02:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app02
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE2_IP}
          aliases: 
              - app02

  app03:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app03
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE3_IP}
          aliases: 
              - app03

  app04:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app04
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE4_IP}
          aliases: 
              - app04

  app05:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app05
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE5_IP}
          aliases: 
              - app05

  app06:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app06
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE6_IP}
          aliases: 
              - app06

  app07:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app07
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE7_IP}
          aliases: 
              - app07

  app08:
    image: thenaim/httpinfo
    container_name: ${PROJECT_NAME}_app08
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - ${NODE_PORT}
    networks:
      public_net:
          ipv4_address: ${NODE8_IP}
          aliases: 
              - app08



networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}